<?php


namespace Controller;

use Core\Config;
use Model\QuestionsModel;
use mysqli;
use View\View;

class QuestionsController extends AbstractTableController
{
    protected $tableName = "questions";
    protected $templateFolder = "questions";
    private $answerVariant = ['A', 'B', 'C', 'D'];
    protected $mylink;

    private function setMyLink($link)
    {
        $this->mylink = $link;
    }

    public function __construct(View $view, mysqli $link)
    {
        parent::__construct($view, $link);
        $this->table = new QuestionsModel(
            $this->tableName,
            $link
        );
        $this->setMyLink($link);
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data);
        $this->view->addData([
            'testsTitleList' => $this->table->getTests(),
            'answerVariant' => $this->answerVariant,
            'table' => $this
                ->table
                ->getQuestions(
                    Config::PAGE_SIZE,
                    $data['get']['page'] ?? 1
                )
        ]);
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data);
        $this->view->addData([
            'testsTitleList' => $this->table->getTests(),
            'answerVariant' => $this->answerVariant
        ]);
    }

    public function actionAdd(array $data)
    {
        session_start();
        $_SESSION['a'] = $data['test_id'];
        echo $_SESSION['a'];
        foreach ($data as &$field) {
            $field['content'] = $this->mylink->real_escape_string($field['content']);
            $field['answer1'] = $this->mylink->real_escape_string($field['answer1']);
            $field['answer2'] = $this->mylink->real_escape_string($field['answer2']);
            $field['answer3'] = $this->mylink->real_escape_string($field['answer3']);
            $field['answer4'] = $this->mylink->real_escape_string($field['answer4']);
        }
        parent::actionAdd($data); // TODO: Change the autogenerated stub
    }
}